### ISSUE TITLE
do you have a pytorch versions

### ISSUE THREAD

**Issue by tanghailong0214** [Sakib1263/ResNet-ResNetV2-SEResNet-ResNeXt-SEResNeXt-1D-2D-Tensorflow-Keras#1]
I am surprised by your extraordinary work. I am more familiar with pytorch, do you plan to release a pytorch version in the future?

**Comment by Sakib1263** [comment]
Hi,

I am actually familiar with Tensorflow. I know only the basics of PyTorch. There are other people in my research team who are experts in PyTorch but they do not share codes. You can try to understand my codes and convert them into PyTorch, I did the opposite for many of my models, I converted PyTorch models into Tensorflow for flexible End2End 1D and 2D classification, regression, and segmentation pipelines (I only shared a few in GitHub, the rest are confidential for our research team, will share slowly after we get some publications on them).
